### ISSUE TITLE
해외 주식 데이터 웹 크롤링 문제

### ISSUE THREAD

**Issue by dnwnsqjarnt** [boring-km/k-stock#23]
#8
![image](https://user-images.githubusercontent.com/39476310/112757335-61dc9300-9024-11eb-8cf0-ce1ac4800523.png)

www.investing.com/stock-screener 에서 제공하는 주식데이터를 웹크롤링할때 값을 제대로 가져오지 못함
다른 사이트를 찾아봐야 할 것 같습니다.

**Comment by boring-km** [comment]
![image](https://user-images.githubusercontent.com/34850203/112975623-d7fd0900-918e-11eb-8d94-7b6b48e5164d.png)
https://finviz.com/screener.ashx?v=111&f=exch_nasd,geo_usa&ft=4
이 사이트에서도 한 번 해볼만한 것 같아서 저도 크롤링 시도해볼께요

**Comment by boring-km** [comment]
![image](https://user-images.githubusercontent.com/34850203/112983753-02ec5a80-9199-11eb-9dbe-b64b25c6acc7.png)

크롤링 잘 됩니다!! @dnwnsqjarnt

**Comment by boring-km** [comment]
미국 주식 거래소 중에 나스닥 주식만 전체를 크롤링 해서 불러와봤더니 140초 정도 걸렸어요.
다른 거래소까지 몽땅 다 불러온다고 생각하면 현실적으로 너무 시간이 오래걸릴 것 같아요. @dnwnsqjarnt 
주식 조회만 하는 서비스는 stock-external이 아니라 stock-api 서버에서 rapid API 호출 결과를 바로 Android로 넘기는 형태로 구현하고,
알림 등록할 때는 stock-core DB에 사용자가 등록한 주식 조회해서, stock-external DB에 주식 종목이 겹치지 않게 등록한 뒤에 실시간으로 rapid API 서비스 하면 될 것 같아요
